CC := avr-gcc
OC := avr-objcopy

CFLAGS += -Os -fno-fat-lto-objects -mcall-prologues -mmcu=atmega8 -DF_CPU=3686400

AVRDUDE_FLAGS := -v -p ATmega8 -c usbasp -U lfuse:w:0xff:m -U hfuse:w:0xc9:m

NAME_HEX := pinkie.hex

SRC += \
    arch/atmega8/pinkie_arch.c

INC += \
    arch/atmega8

PINKIE_PLAT_ATMEGA = y
PINKIE_NVS_ATMEGA = y
PINKIE_SPI_ATMEGA = y
PINKIE_MOD_ATMEGA_STACKPAINT = y
